version: '3'

vars:
  DEVBOX_DIR_PATH: "$HOME/.local/share/devbox/global/default"

tasks:
  default:
    cmds:
      - task help
    silent: true

  help:
    cmds:
      - echo "Welcome to my project - maintainer<Tommy Tran Duc Thang> - email<tommytran.dev@gmail.com>"
      - echo "Run task <task_name> to run predefined script"
      - echo ""
      - echo "For setting up the environment            task local:install"
      - echo ""
      - task -l
    silent: true

  setup:
    desc: "install the environment, setup env for macOS and Ubuntu. To force update existing files run: task setup -- force"
    vars:
      COPYDOTFILES_MODE: "{{.CLI_ARGS}}"
    cmds:
      - echo "----------------------------------------------------------------"
      - echo "This requires sudo permission to run"
      - echo "Are you okay with it? This only uses the role to create symblink"
      - echo "----------------------------------------------------------------"
      - sudo echo "Starting to setup system"
      - echo "----------------------------------------------------------------"
      - command -v devbox &> /dev/null || { curl -fsSL https://get.jetify.com/devbox | bash; }
      - sh -c '[ -d "{{.DEVBOX_DIR_PATH}}" ] || mkdir -p "{{.DEVBOX_DIR_PATH}}"'
      - ln -sf "$(pwd)/devbox.json" "{{.DEVBOX_DIR_PATH}}/devbox.json"
      # - ln -sf "$(pwd)/devbox.lock" "{{.DEVBOX_DIR_PATH}}/devbox.lock"
      - devbox global install 
    silent: true

  copydotfiles:
    desc: create symlink to dotfiles
    vars:
      COPYDOTFILES_MODE: '{{default "" .COPYDOTFILES_MODE}}' 
    env: 
      FORCE_FLAG: ""
    internal: false
    silent: false
    cmds: 
      - |
        if [ "{{.COPYDOTFILES_MODE}}" = "force" ]; then FORCE_FLAG="-f"; fi
        ln -s ${FORCE_FLAG} "$(pwd)/config/ags"               "$HOME/.config/ags"
        ln -s ${FORCE_FLAG} "$(pwd)/config/hypr"               "$HOME/.config/hypr"
        ln -s ${FORCE_FLAG} "$(pwd)/config/nvim"               "$HOME/.config/nvim"
        ln -s ${FORCE_FLAG} "$(pwd)/config/.tmux.conf"        "$HOME/.tmux.conf"
